[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = [
    "pip install --no-cache-dir torch==2.2.0 torchvision==0.17.0 --index-url https://download.pytorch.org/whl/cpu",
    "pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "python main.py"
